export { ClockBoard } from './ClockBoard'
export { clock, clockCycle, clockRandom, type ClockOptions, type ClockShowcaseOptions } from './behaviors/clock'
export { cycle, random, type CycleRandomOptions } from './behaviors/cycle'
export { ALL_PATTERNS, BLOOM, CHECKERBOARD, CHEVRONS, CONCENTRIC_RECTS, CONVERGE, CROSS_STITCH, NOON, RADIAL, randomPattern, RINGS, SPIRAL_ARMS, VORTEX, WAVE, WINDMILL } from './patterns/ambient'
export { composeTime } from './patterns/time'
export type { ApplyPattern, Behavior, ClockBoardProps, ClockState, GridPattern } from './types'
